blogpessoal/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls')),
]

posts/urls.py
from django.urls import path
from .views import Index, List, Detail, Create, Update, Delete, Comment, Categories, Category
from . import views

urlpatterns = [
    path('list/', List.as_view(), name='list'),
    path('', Index.as_view(), name='index'),
    path('list/search/', views.search_posts, name='search'),
    path('list/create/', Create.as_view(), name='create'),
    path('list/<int:pk>/', Detail.as_view(), name='post-detail'),
    path('list/update/<int:pk>/', Update.as_view(), name='update'),
    path('list/delete/<int:pk>/', Delete.as_view(), name='delete'),
    path('list/<int:pk>/comment', Comment.as_view(), name="comment"),
    path('categories/', Categories.as_view(), name='categories'),
    path('categories/<int:pk>/', Category.as_view(), name='category-detail'),
]

posts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from datetime import datetime, date

class Category(models.Model):
    title = models.CharField(max_length=255)
    body  = models.TextField()

    def __str__(self):
        return self.title

class Post(models.Model):
    categories = models.ManyToManyField(Category, blank=False, related_name="posts")
    title = models.CharField(max_length=255)
    author = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    imageURL = models.URLField(max_length=300)
    datetime = models.DateTimeField(auto_now_add=True)
    body  = models.TextField()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('post-detail', kwargs={'pk': self.pk})

class Comment(models.Model):
    post = models.ForeignKey(Post, related_name='comments', on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    datetime = models.DateTimeField(auto_now_add=True)
    body  = models.TextField()

    def __str__(self):
        return '%s - %s' %(self.post.title, self.author)

posts/forms.py
from django import forms
from .models import Post, Comment, Category

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('categories','title', 'author', 'imageURL', 'body')

        widgets = {
            'categories': forms.CheckboxSelectMultiple(attrs={'class': 'form-control'}),
            'title': forms.TextInput(attrs={'class': 'form-control form-control-lg', 'placeholder': 'O título da sua postagem', 'label': 'alo'}),
            'author': forms.Select(attrs={'class': 'form-control'}),
            'imageURL': forms.URLInput(attrs={'class': 'form-control', 'placeholder': 'Link de uma imagem associada à postagem'}),
            'body': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'O conteúdo da postagem'}),
        }

class EditForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('categories','title', 'imageURL', 'body')

        widgets = {
            'categories': forms.CheckboxSelectMultiple(attrs={'class': 'form-control'}),
            'title': forms.TextInput(attrs={'class': 'form-control form-control-lg', 'placeholder': 'O título da sua postagem', 'label': 'alo'}),
            'imageURL': forms.URLInput(attrs={'class': 'form-control', 'placeholder': 'Link de uma imagem associada à postagem'}),
            'body': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'O conteúdo da postagem'}),
        }

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('author', 'body')

        widgets = {
            'author': forms.Select(attrs={'class': 'form-control'}),
            'body': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'O conteúdo do comentário'}),
        }

posts/views.py
from django.shortcuts import render
from .models import Post, Comment, Category
from django.urls import reverse
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.shortcuts import render, get_object_or_404
from .forms import PostForm, EditForm, CommentForm
from django.urls import reverse_lazy

class Index(ListView):
    model = Post
    template_name = 'posts/index.html'

def search_posts(request):
    context = {}
    if request.GET.get('query', False):
        search_term = request.GET['query'].lower()
        post_list = Post.objects.filter(title__icontains=search_term)
        context = {"post_list": post_list}
    return render(request, 'posts/search.html', context)

class List(ListView):
    model = Post
    template_name = 'posts/list.html'
    ordering = ['-datetime'] 

class Detail(DetailView):
    model = Post
    template_name = 'posts/detail.html'

class Create(CreateView):
    model = Post
    form_class = PostForm
    template_name = 'posts/create.html'

class Update(UpdateView):
    model = Post
    form_class = EditForm
    template_name = 'posts/update.html'

class Delete(DeleteView):
    model = Post
    template_name = 'posts/delete.html'
    success_url = reverse_lazy('list')

class Comment(CreateView):
    model = Comment
    form_class = CommentForm
    template_name = 'posts/comment.html'

    def form_valid(self, form):
        form.instance.post_id = self.kwargs['pk']
        return super().form_valid(form)
    
    def get_success_url(self):
        return reverse_lazy('post-detail', kwargs={'pk': self.kwargs['pk']})

class Categories(ListView):
    model = Category
    template_name = 'posts/categories.html'

class Category(DetailView):
    model = Category
    template_name = 'posts/category.html'

posts/templates/posts/categories.html
{% extends 'base.html' %}
{% block title%} Categorias {% endblock %}
{% block content %}

<h1>Categorias</h1>
{% if category_list %}
    <ul>
    {% for category in category_list %}
        <li> <a href="{% url 'category-detail' category.pk %}"><strong>{{ category.title }}</strong> </a> - 
            {{ category.body|safe}} </li> 
        <br>
    {% endfor %}
    </ul>
{% else %}
<a href="{% url 'index' %}" class="btn btn-primary">Home </a>
{% endif %}


{% endblock %}

posts/templates/posts/category.html
{% extends 'base.html' %}
{% block title %} {{ category }} {% endblock %}
{% block content %}

<h1>{{ category.title}}</h1>
{% if not category.posts.all %}
    <p>Não há posts para mostrar</p>
{% else %}
    {% for post in category.posts.all %}
    <ul>
        <li> <a href="{% url 'post-detail' post.pk %}"><strong>{{ post.title }}</strong> </a> - 
            <small>{{ post.author.first_name}} {{post.author.last_name }}</small> <br>
            <small>{{ post.datetime }}</small> <br>
            {{ post.body|slice:":290"|safe}} </li> 
        <br>
    </ul>
    {% endfor %}
{% endif %}

{% endblock %}

posts/templates/posts/comment.html
{% extends 'base.html' %}
{% block title%} Comentar {% endblock %}

{% block content %}

<h1>Comentário</h1>
<br>

<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button class="btn btn-success">Comentar</button>

{% endblock %}

posts/templates/posts/create.html
{% extends 'base.html' %}

{% block content %}
<h2>Inserir Novo Post</h2>
<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button class="btn btn-success">Publicar</button>

{% endblock content %}

posts/templates/posts/delete.html
{% extends 'base.html' %}

{% block content %}
<form action="{% url 'delete' post.id %}" method="post">
    {% csrf_token %}
    <p>
        Você tem certeza que deseja apagar o post "{{ post.title }} ({{ post.datetime }})"?
    </p>
    <button type="submit">Apagar</button>
</form>

{% endblock content %}

posts/templates/posts/detail.html
{% extends 'base.html' %}

{% block title %}
{{ post.title }} ({{ post.datetime }}
{% endblock title %}

{% block content %}
<br>
<b>Categorias:</b> {% for category in post.categories.all %}
<a href="{% url 'category-detail' category.id %}">{{ category.title }}</a> -
{% endfor %}
<h2>{{ post.title }}</h2>
<small> Por: {{ post.author.first_name }} {{ post.author.last_name }} <br>
    Data: {{ post.datetime }} </small>
    <section class="editarapagar">
        <ul>
            <li><a href="{% url 'update' post.id %}">Editar</a></li>
            <li><a href="{% url 'delete' post.id %}">Apagar</a></li>
        </ul>
    </section>
<p>{{ post.body }}</p>
<img src="{{ post.imageURL }}" alt="Imagem {{ post.title}}" width="30%">
<hr>
<h3>Comentários</h3>

{% if not post.comments.all %}
    <small>Ainda não há comentários para esta publicação...</small>
    <br><br>
    <a href="{% url 'comment' post.pk %}" class="btn btn-dark btn-sm">Adicionar Comentário</a>
    <br><br>
{% else %}
    <a href="{% url 'comment' post.pk %}" class="btn btn-dark btn-sm">Adicionar Comentário</a> <br><br>
    {% for comment in post.comments.all %}
        <strong>{{ comment.author.first_name }} {{ comment.author.last_name }}</strong> <small>- {{ comment.datetime }}</small>
        <br>{{ comment.body }} <br><br>
    {% endfor %}
{% endif %}

<br>

{% endblock content %}

posts/templates/posts/index.html
{% extends 'base.html' %}

{% block title %}
Página Inicial
{% endblock title %}

{% load static %}
{% block content %}
<h1>Sobre</h1>
<div class="single">
    <div class="singleimage">
        <img src="{% static 'euimage.jpg' %}" alt="tumimage" width="200px">
    </div>
    <div class="singlecontent">
        Esse blog é destinado a informações acadêmicas e profissionais. Além disso, é possível conferir posts sobre atividades realizadas e entrar em contato para oportunidades. Sou estudante de engenharia mecatrônica na Escola Politécnica da Universidade de São Paulo. Interessado em tecnologia, robótica, programação, empreendedorismo, design gráfico e experiências internacionais. Sempre buscando novas oportunidades.
    </div>
</div>
<h2>Currículo</h2>
<lo>
    <li><a href="https://drive.google.com/file/d/150Tg-wnHdKWUJLW3Oh-O-gGoFWhN-rVs/view?usp=sharing">Completo</a></li>
    <li><a href="https://drive.google.com/file/d/12BU5vlhpu91q3yoDIJwJEFBycoLxkh7w/view?usp=sharing">Profissional</a></li>
</lo> 
<h2>Redes Sociais</h2>
<lo>
    <li><a href="https://www.linkedin.com/in/nicolas-nabrink">Linkedin</a></li>
    <li><a href="https://www.instagram.com/nicolas_nabrink/?hl=en">Instagram</a></li>
</lo> 
<h2>Contato</h2>
<lo>
    <li>Pessoal/Profissional: nicolas@nabrink.com.br</li>
    <li>Acadêmico: nicolas_nabrink@usp.br</li>
</lo> 
{% endblock content %}

posts/templates/posts/list.html
{% extends 'base.html' %}
{% block title%} Postagens {% endblock %}
{% block content %}

<h1>Postagens</h1>
<p>Muitos resultados? <a href="{% url 'search' %}">Buscar post</a></p>
<p>Deseja criar um post? <a href="{% url 'create' %}">Adicionar Novo Post</a></p>
{% if post_list %}
    <ul>
    {% for post in post_list %}
        <li> <a href="{% url 'post-detail' post.pk %}"><strong>{{ post.title }}</strong> </a> - 
            <small>{{ post.author.first_name}} {{post.author.last_name }}</small> <br>
            <small>{{ post.datetime }}</small> <br>
            <small>{% for category in post.categories.all %}<a href="{% url 'category-detail' category.id %}">{{ category.title }}</a> -{% endfor %}</small><br>
            {{ post.body|slice:":290"|safe}} </li> 
        <br>
    {% endfor %}
    </ul>
{% else %}
<a href="{% url 'index' %}" class="btn btn-primary">Home </a>
{% endif %}

{% endblock %}

posts/templates/posts/search.html
{% extends 'base.html' %}

{% block content %}
<h2>Busca de post por título</h2>
<form action="{% url 'search' %}">
    <p>
        <label for="id_query">Título:</label>
        <input type="text" name="query" id="id_query" />
    </p>
    <button type="submit">Buscar</button>
</form>


<h2>Resultado da Busca</h2>
{% if post_list %}
<section class="lista-de-cards">
    {% for post in post_list %}
    <article class="card">
        <img src="{{ post.imageURL }}" alt="Poster do filme {{ post.title}}" width="30%">
        <a href="{% url 'post-detail' post.pk %}"><strong>{{ post.title }}({{ post.datetime }})</strong> </a>
    </article>
    {% endfor %}
</section>
{% else %}
<p>Não foi encontrado nenhum post para a busca.</p>
{% endif %}

{% endblock content %}

posts/templates/posts/update.html
{% extends 'base.html' %}
{% block title%} Editar Postagem {% endblock %}

{% block content %}

<h1>Editar Conteúdo</h1>
<br><br>

<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button class="btn btn-success">Atualizar</button>

{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link href="https://fonts.googleapis.com/css?family=Inter&display=swap" rel="stylesheet" />
        <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
        <title>{% block title %}{% endblock %} | Nicolas Nabrink</title>
    </head>

<body>
    <header>
        <img src="{% static 'tumimage.jpg' %}" alt="tumimage" width="100%">
        <div class="title"> 
            <h1>Nicolas Nabrink</h1>
        </div>
        <nav>
            <div class="button"> 
                <button><a href="{% url 'index' %}">Home</a></button>
                <button><a href="{% url 'list' %}">Posts</a></button>
                <button><a href="{% url 'categories' %}">Categorias</a></button>
            </div>
        </nav>
    </header>
    <main>
        {% block content %}
        {% endblock content %}
    </main>
    <footer>
        <p>Copyright 2022 Nicolas Nabrink.</p>
    </footer>
</body>

</html>